install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3

language: erlang

notifications:
  email: false

otp_release:
  - 18.0
  - 19.3
  - 20.0

script: "./rebar3 as test clean, eunit"

sudo: false